version: "3.4"
services:
   web:
       build: .
       command:  sh -c "python manage.py collectstatic --no-input && yes | python manage.py migrate && python manage.py makemigrations polls && python manage.py migrate && python manage.py runserver 0.0.0.0:81"
       volumes:
        - .:/app
       ports:
           - 81:81
    
